proto_library(
    name = 'serviceproto',
    srcs = [
        'newsad.proto',
        'mq.proto',
        'newsrcm.proto',
        'profile.proto',
        'newstrigger.proto',
        'policy.proto',
        'luacall.proto',
        'ranking.proto',
        'simhisfilter.proto',
        'feedback.proto',
        'rankingusersessioninfo.proto',
        'rerank.proto',
        'cf.proto',
        'videoprofile.proto',
        'segment.proto',
        'profileext.proto',
        'partition.proto',
		'service.proto',
    ],
)

cc_binary(
    name = 'rpcproto',
    srcs = [
        'rpcproto.cc',
    ],
    deps = [
    ],
)




