proto_library (
    name = "indexing_proto",
    srcs = [
        "docinfo_type.proto",
        "generic_docinfo.proto",
        "index_server.proto",
        "indexing_meta.proto",
        "inverted_index_load_dump_struct.proto",
        "search_conf.proto",
        "search_param.proto",
    ],
)
