/* This file was generated by blade */
extern "C" {
namespace binary_version {
extern const int kSvnInfoCount = 1;
extern const char* const kSvnInfo[1] = {"git@github.com:mp2mp-developer/mp2mp.git\n"
"* ys-dev\n"
"commit 1e0c92beeec023b6c10275ced61c68599b010756\n"
"Author: YoungAndSure <yangshuorex@foxmail.com>\n"
"Date:   Sun Oct 21 17:25:21 2018 +0800\n"
"\n"
"    add not_daemon.sh && fix code\n"
""};
extern const char kBuildType[] = "release";
extern const char kBuildTime[] = "Sun Oct 21 22:48:40 2018";
extern const char kBuilderName[] = "youngsure";
extern const char kHostName[] = "Young";
extern const char kCompiler[] = "GCC 7";
}}
